name: Run Tests

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the tellor branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-22.04
    env:
      NIGHTLY: nightly-2023-02-01 # Fix version to prevent cache misses with nightly changes

    steps:
      - uses: actions/checkout@v3

      - name: Set-Up
        run: sudo apt update && sudo apt install -y git clang curl libssl-dev llvm libudev-dev cmake protobuf-compiler

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Install Nightly
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.NIGHTLY }}
          override: true
          target: wasm32-unknown-unknown

      - name: Cache Build artefacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            runtime-api/target/
          key: ${{ runner.os }}-cargo-test-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-test

      - name: test
        run: | 
          RUSTFLAGS="-C instrument-coverage" cargo test --tests                                        

